### ISSUE TITLE
Nightlight depends on clojure 1.9 but doesn't.

### ISSUE THREAD

**Issue by phillord** [oakes/Nightlight#51]
Just upgraded to 2.1.3 (from 1.9 something or other).

I am getting an exception (see below). It's possible to workaround by
specifically adding Clojure 1.9 as a dependency. I think the error comes
from dynadoc actually, but I can't quite see where or why nightlight depends
on it.

Anyway, practical upshot. Nightlight appears to depend on Clojure 1.9
(or spec anyway), but doesn't explicitly state so in it's pom.

Thanks for the project; great tool.

    Exception in thread "main" java.io.FileNotFoundException: Could not locate clojure/spec/alpha__init.class or clojure/spec/alpha.clj on classpath., compiling:(dynadoc/example.clj:1:1)
    	at clojure.lang.Compiler.load(Compiler.java:7239)
    	at clojure.lang.RT.loadResourceScript(RT.java:371)
    	at clojure.lang.RT.loadResourceScript(RT.java:362)
    	at clojure.lang.RT.load(RT.java:446)
    	at clojure.lang.RT.load(RT.java:412)
    	at clojure.core$load$fn__5448.invoke(core.clj:5866)
    	at clojure.core$load.doInvoke(core.clj:5865)
    	at clojure.lang.RestFn.invoke(RestFn.java:408)
    	at clojure.core$load_one.invoke(core.clj:5671)
    	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    	at clojure.core$load_lib.doInvoke(core.clj:5710)
    	at clojure.lang.RestFn.applyTo(RestFn.java:142)
    	at clojure.core$apply.invoke(core.clj:632)
    	at clojure.core$load_libs.doInvoke(core.clj:5749)
    	at clojure.lang.RestFn.applyTo(RestFn.java:137)
    	at clojure.core$apply.invoke(core.clj:632)
    	at clojure.core$require.doInvoke(core.clj:5832)
    	at clojure.lang.RestFn.invoke(RestFn.java:436)
    	at eval_soup.core$eval545$loading__5340__auto____546.invoke(core.clj:1)
    	at eval_soup.core$eval545.invoke(core.clj:1)
    	at clojure.lang.Compiler.eval(Compiler.java:6782)
    	at clojure.lang.Compiler.eval(Compiler.java:6771)
    	at clojure.lang.Compiler.load(Compiler.java:7227)
    	at clojure.lang.RT.loadResourceScript(RT.java:371)
    	at clojure.lang.RT.loadResourceScript(RT.java:362)
    	at clojure.lang.RT.load(RT.java:446)
    	at clojure.lang.RT.load(RT.java:412)
    	at clojure.core$load$fn__5448.invoke(core.clj:5866)
    	at clojure.core$load.doInvoke(core.clj:5865)
    	at clojure.lang.RestFn.invoke(RestFn.java:408)
    	at clojure.core$load_one.invoke(core.clj:5671)
    	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    	at clojure.core$load_lib.doInvoke(core.clj:5710)
    	at clojure.lang.RestFn.applyTo(RestFn.java:142)
    	at clojure.core$apply.invoke(core.clj:632)
    	at clojure.core$load_libs.doInvoke(core.clj:5749)
    	at clojure.lang.RestFn.applyTo(RestFn.java:137)
    	at clojure.core$apply.invoke(core.clj:632)
    	at clojure.core$require.doInvoke(core.clj:5832)
    	at clojure.lang.RestFn.invoke(RestFn.java:2422)
    	at nightlight.core$eval9$loading__5340__auto____10.invoke(core.clj:1)
    	at nightlight.core$eval9.invoke(core.clj:1)
    	at clojure.lang.Compiler.eval(Compiler.java:6782)
    	at clojure.lang.Compiler.eval(Compiler.java:6771)
    	at clojure.lang.Compiler.load(Compiler.java:7227)
    	at clojure.lang.RT.loadResourceScript(RT.java:371)
    	at clojure.lang.RT.loadResourceScript(RT.java:362)
    	at clojure.lang.RT.load(RT.java:446)
    	at clojure.lang.RT.load(RT.java:412)
    	at clojure.core$load$fn__5448.invoke(core.clj:5866)
    	at clojure.core$load.doInvoke(core.clj:5865)
    	at clojure.lang.RestFn.invoke(RestFn.java:408)
    	at clojure.core$load_one.invoke(core.clj:5671)
    	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    	at clojure.core$load_lib.doInvoke(core.clj:5710)
    	at clojure.lang.RestFn.applyTo(RestFn.java:142)
    	at clojure.core$apply.invoke(core.clj:632)
    	at clojure.core$load_libs.doInvoke(core.clj:5749)
    	at clojure.lang.RestFn.applyTo(RestFn.java:137)
    	at clojure.core$apply.invoke(core.clj:632)
    	at clojure.core$require.doInvoke(core.clj:5832)
    	at clojure.lang.RestFn.invoke(RestFn.java:408)
    	at user$eval5.invoke(form-init6082467032111694581.clj:1)
    	at clojure.lang.Compiler.eval(Compiler.java:6782)
    	at clojure.lang.Compiler.eval(Compiler.java:6771)
    	at clojure.lang.Compiler.load(Compiler.java:7227)
    	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    	at clojure.main$load_script.invoke(main.clj:275)
    	at clojure.main$init_opt.invoke(main.clj:280)
    	at clojure.main$initialize.invoke(main.clj:308)
    	at clojure.main$null_opt.invoke(main.clj:343)
    	at clojure.main$main.doInvoke(main.clj:421)
    	at clojure.lang.RestFn.invoke(RestFn.java:421)
    	at clojure.lang.Var.invoke(Var.java:383)
    	at clojure.lang.AFn.applyToHelper(AFn.java:156)
    	at clojure.lang.Var.applyTo(Var.java:700)
    	at clojure.main.main(main.java:37)
    Caused by: java.io.FileNotFoundException: Could not locate clojure/spec/alpha__init.class or clojure/spec/alpha.clj on classpath.
    	at clojure.lang.RT.load(RT.java:449)

**Comment by oakes** [comment]
Ah, good point. The real cause of this is that [defexample](https://github.com/oakes/defexample) is using clojure.spec. I believe at least two libraries that Nightlight uses depend on defexample: eval-soup and Dynadoc. I could actually fix this by using [clojure-future-spec](https://github.com/tonsky/clojure-future-spec) but since 1.9 is out now perhaps it's best to just require it. I'm not sure what the best thing to do is regarding the pom file. Normally people suggest always making clojure as `:scope "provided"` so it doesn't show up there at all.

**Comment by phillord** [comment]
For my use case, requiring Clojure 1.9 is not a problem. The library that I am editing with nightlight only requires 1.7, though. And leiningen by default seems to be conservative with Clojure versions -- if you say "1.7" this is what it uses, although it could validly choose to use 1.9 assuming some semantics to versioning.

I'm a bit dubious about `:scope provided`. I mean, what if I embed clojure in a Java application to provide scripting abilities for that application? If clojure isn't mentioned, it is not going to work. And, as this example shows, if clojure is marked as provided, how will anyone know what version of clojure we should be using?

**Comment by danielo515** [comment]
Hello,

I don't have much experience with clojure. Could you provide more detailed instructions about how to fix this ? I'm already using clojure 1.9.0

**Comment by danielo515** [comment]
Ok, seems that you have to require clojure 1.9.0 specifically. I was requiring an alpha.

here is the head of my project.clj working

```clj
(defproject hello-world "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"

  :min-lein-version "2.7.1"

  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.9.908"]
                 [nightlight "RELEASE"]]

```
