### ISSUE TITLE
Docs: (lein) Project needs to be Clojure 1.5+

### ISSUE THREAD

**Issue by winks** [oakes/Nightlight#7]
I got this error:

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate clojure/edn__init.class or clojure/edn.clj on classpath: 
    at clojure.lang.RT.load(RT.java:432)
    at clojure.lang.RT.load(RT.java:400)
    at clojure.core$load$fn__4890.invoke(core.clj:5415)
    at clojure.core$load.doInvoke(core.clj:5414)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5227)
    at clojure.core$load_lib.doInvoke(core.clj:5264)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$load_libs.doInvoke(core.clj:5298)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.core$require.doInvoke(core.clj:5381)
    at clojure.lang.RestFn.invoke(RestFn.java:1096)
    at nightlight.core$eval9$loading__4784__auto____10.invoke(core.clj:1)
    at nightlight.core$eval9.invoke(core.clj:1)
```

and found this solution:
https://github.com/rkneufeld/lein-try/issues/14

i.e. using Clojure 1.5.0 and not 1.4.0 in my project.clj.

//edit:
To clarify: this is not a problem, more like 'this should work from Clojure 1.5 and newer'

**Comment by oakes** [comment]
Thank you. I think it's uncommon enough that it isn't necessary, since at the end of the day it's just a library, and all Clojure libraries potentially have this issue.
